# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proto < Formula
  desc "Install and manage custom Proton installations with ease"
  homepage "https://github.com/BitsOfAByte/proto"
  version "0.7.0"
  license "GPL-3.0-only"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BitsOfAByte/proto/releases/download/v0.7.0/proto_linux_arm.zip"
      sha256 "8e5164086f6e7171847f90708da0bbacf972766541418dd6d22573a1337228b2"

      def install
        bin.install "proto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BitsOfAByte/proto/releases/download/v0.7.0/proto_linux_arm64.zip"
      sha256 "c8d0d0f2ea192582d11560a0fd7b76b0398e9b0dc58ebfc004fafbab52bcf4b7"

      def install
        bin.install "proto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BitsOfAByte/proto/releases/download/v0.7.0/proto_linux_amd64.zip"
      sha256 "c2d8555de3f0dae3c91676a794acd0bebdf6f60211e4cb19adf2c4362603b898"

      def install
        bin.install "proto"
      end
    end
  end
end
