# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proto < Formula
  desc "Proto compatability tool manager
"
  homepage "https://github.com/ProtoSoftware/proto"
  version "0.8.3"
  license "GPL-3.0-only"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ProtoSoftware/proto/releases/download/v0.8.3/proto_linux_arm64.zip"
      sha256 "7a22d01cae2e5c56ff18d77bfd29e894067408726af47df95c38993631dee963"

      def install
        bin.install "proto"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ProtoSoftware/proto/releases/download/v0.8.3/proto_linux_arm.zip"
      sha256 "517c72154a8a3766a2b3eabc087f2abd1b166773e1bb957a7114200502366158"

      def install
        bin.install "proto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ProtoSoftware/proto/releases/download/v0.8.3/proto_linux_amd64.zip"
      sha256 "7622b340c03ad9f39215af9eeb3682f5ee4119936a9f04d9586b8a55be68b90d"

      def install
        bin.install "proto"
      end
    end
  end

  depends_on "gnu-tar"
end
