# This workflow outlines tasks that are ran when a pull request that modifies source code is made, such as building a preview

name: "PR: Code Changes"

on:
  pull_request:
    branches: [main]
    types: ["ready_for_review"]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".goreleaser.yml"

jobs:
  # Check to see if an invalid file has been modified, if it has then fail.
  No-Invalid-Edits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Edited Files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: "json"
          filters: |
            src:
              - 'proto.rb'

      - name: Post Comment on Invalid Changes
        if: steps.changes.outputs.src == 'true'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "A preview build was not generated as a security measure as invalid files have been modified, please refer to the contributing guide for information."
          comment_includes: "preview build"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail CI on Invalid Edit
        if: steps.changes.outputs.src == 'true'
        run: |
          echo "::error::Contains invalid file edits"
          exit 1

  # Check to see if any new dependency in this pull request is vulnerable.
  Dependency-Review:
    runs-on: ubuntu-latest
    needs: ["No-Invalid-Edits"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v1

      - name: Post Comment on Insecure Changes
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "A preview build was not generated as a security measure due to this pull request containing insecure dependencies."
          comment_includes: "preview build"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # If all is good, create a preview build for the pull request if needed.
  Preview:
    runs-on: ubuntu-latest
    needs: ["Dependency-Review", "No-Invalid-Edits"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.2

      - name: Restore Build Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Assets
        uses: actions/upload-artifact@v3
        with:
          path: |
            dist/proto*_*/*
            checksums.txt

      - name: Edit Comment (Success)
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ### ✅ Success

            **Always review the source code before executing it on your system, no matter where it comes from** 

            | Name                 |  Link                                                                          |
            |----------------------|--------------------------------------------------------------------------------|
            | Preview Build Commit | ${{ github.sha }}                                                              |
            | Preview Build URL    |  https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} |
          comment_includes: "preview build"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Edit Comment (Failure)
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "Deploy failed! Something went wrong while generating a preview build for this pull request."
          comment_includes: "preview build"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
